### ISSUE TITLE
Wrong Dict Key

### ISSUE THREAD

**Issue by rahulvigneswaran** [qihongl/nnsrm-neurips18#1]
In `demo-nnalign.ipynb`, in [this cell](https://colab.research.google.com/github/qihongl/demo-nnalign/blob/master/demo-nnalign.ipynb#scrollTo=ZSk9ASJ0p4RB&line=4&uniqifier=1), the Dict keys are, `acc` and `val_acc`, not `accuracy` and `val_accuracy`.

**Comment by qihongl** [comment]
Ah thanks! kera changed these key names in a new version. I should update these things.

**Comment by rahulvigneswaran** [comment]
Since Google Colab uses TF2 by default now, there are a lot of errors. Using `%tensorflow_version 1.x` before all the code subsides the majority of the issue. Yet there are some major errors due to version deferences of other packages.

**Comment by qihongl** [comment]
Ah thank you very much for letting me know! I wasn't expecting version-related issues back then. Definitely want to update the code when I have some time.

**Comment by rahulvigneswaran** [comment]
Understandable. I am currently trying to interpret the code to understand the paper better, kindly help me out if I bump into some code related issues that I can't figure out. Feel free to close this issue if necessary.
